language: node_js
node_js:
- '6'
- '7.5'
after_success:
- npm run coverage
deploy:
  provider: npm
  email: pragmaticivan@gmail.com
  on:
    tags: true
  api_key:
    secure: n1yoPgcZ4XyBg5PpQQXUiTQHZcBFQ6IiMZn9K62/9R+WyalRj6f88fJqvvfXXnGw88gML+vRUaG/ooSFWPRKB9jQcY7TSuzUpngEG3j0mtz34mcGHbCYqCbyy9aQbHt7x/b2I6HT6e8HaewuoDU2zXWeSAw/vT+Gmw6fhVdSqfpugSLWd81fHAqTmZcOWT+DD0ko5rK05yPmExJdPH7uGcOIoTw8FcHT6NqN/Rh9Me3izWwslaQtC0rVYPrwsgvaIhQtcZ08YmOi+XooaW8CYT1jKummcuchalYLXWAHbzDsH7/KX+Yuk8reJEZj0PpbAbDLMfZWm5RzS43R0+h6L4DKXRChC947o8d7cD2ne55bMkeHxOrKDmhu6pT0Ox75+vD8MiVVDcVyf16NF5YdcpPq+8MBr5bvISsHDwRmi95QiSfxplekqDhMx2uD+7Op0fz+GDGmvC8hCYuddWfGflkVMIvsEsGh+ipi+2xmGqsIfJZCXIwVq4N47rvMW4vQNZKTPHOMMqQbUkCGP+6USNSYq312BFiBnHVggLeBfXgb5aZdxD3dHVfiCg86i/AKTiEnESPIqasgJSjWEOHe0LK7aF1XRW7B7Wuu2fddi9Eqrnd20iAzcL0/+rNxlX4/wCvrBkK9JldASJuiQIuq5AMziRHJk3WhnzsYL2CFW6I=
addons:
  jwt:
    secure: N98IOBkarVnvIlLez1GMfYJqzZT93unlDI4GrNpjzhBRV4iLoESe8UFQ28IghsugH8zXLsFMB31M70pxQappO6iHzHIix7LQOR4AF2AjUmHbI6lnlHAtDonRr6tSSd2B+vzVJQO27AOk2Rqphr0l551rg2+yXvW1DVV4Y2Stig3W6OQryvQTlndTpRdvpHbk0uZ1KR0/Vv60daRLmdqaNDQ/sGfNCzvo703VOZ0EFsNxBfD/KPunoAtmDYgHl10Hqj3241bBTFvTwVRziMqCCh8nOFnkmPgEzcFfe/C1sWt7tx5zOSvuTZxJj91xBrw+XLIX3ZWQ61c/KyFaU5qoJQTrV5lw1TgCF15HygEi/fwRONqYa45r8PnFzZfY7mPMGtnvZizTHSewALCo5lPOy27GqoURawhis+nGFOOOOhL+IqeRYX6JhD5TqGQRnol8O/NFAUTLdzqTB/YJSrQtBy+z/8Db1EkUdEA2m8U6PQdwe7mKafuOnqWufLvQVm+dmIYQlrePKkapbXU2IcfgpLRYKxE9VcU5NdNuN3yT1KiGvAVfcBhHn9nWp5wd4+BLB1d6piaefY5nKMNA9zrOYWv9SEKsKZNRPFzzaZH2vccS+nMTwq/z/AiX2OwVO2lwdLZ9QhUhPesU9r8Ke/KeqCbrOQvbW409GES5Ng0oqrI=
